// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service.proto

package com.limaopu.grpc.proto;

public final class MyServiceProto {
  private MyServiceProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_RpcRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_RpcRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_RpcResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_RpcResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_RpcJsonRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_RpcJsonRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_RpcJsonResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_RpcJsonResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rservice.proto\022\005proto\"8\n\nRpcRequest\022\r\n\005" +
      "route\030\001 \001(\t\022\r\n\005token\030\002 \001(\t\022\014\n\004data\030\003 \001(\014" +
      "\":\n\013RpcResponse\022\014\n\004code\030\001 \001(\005\022\017\n\007message" +
      "\030\002 \001(\t\022\014\n\004data\030\003 \001(\014\"-\n\016RpcJsonRequest\022\r" +
      "\n\005route\030\001 \001(\t\022\014\n\004data\030\002 \001(\t\">\n\017RpcJsonRe" +
      "sponse\022\014\n\004code\030\001 \001(\005\022\017\n\007message\030\002 \001(\t\022\014\n" +
      "\004data\030\003 \001(\t2\205\001\n\tMyService\0225\n\nRpcExecute\022" +
      "\021.proto.RpcRequest\032\022.proto.RpcResponse\"\000" +
      "\022A\n\016RpcJsonExecute\022\025.proto.RpcJsonReques" +
      "t\032\026.proto.RpcJsonResponse\"\000B=\n\026com.limao" +
      "pu.grpc.protoB\016MyServiceProtoP\001Z\021grpc-my" +
      "boot/protob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_proto_RpcRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_proto_RpcRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_RpcRequest_descriptor,
        new java.lang.String[] { "Route", "Token", "Data", });
    internal_static_proto_RpcResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_proto_RpcResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_RpcResponse_descriptor,
        new java.lang.String[] { "Code", "Message", "Data", });
    internal_static_proto_RpcJsonRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_proto_RpcJsonRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_RpcJsonRequest_descriptor,
        new java.lang.String[] { "Route", "Data", });
    internal_static_proto_RpcJsonResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_proto_RpcJsonResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_RpcJsonResponse_descriptor,
        new java.lang.String[] { "Code", "Message", "Data", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
