// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service.proto

package com.limaopu.grpc.proto;

public interface RpcJsonRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.RpcJsonRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string route = 1;</code>
   * @return The route.
   */
  java.lang.String getRoute();
  /**
   * <code>string route = 1;</code>
   * @return The bytes for route.
   */
  com.google.protobuf.ByteString
      getRouteBytes();

  /**
   * <code>string data = 2;</code>
   * @return The data.
   */
  java.lang.String getData();
  /**
   * <code>string data = 2;</code>
   * @return The bytes for data.
   */
  com.google.protobuf.ByteString
      getDataBytes();
}
