// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user.proto

package com.limaopu.grpc.proto;

public final class UserProto {
  private UserProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_User_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_User_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nuser.proto\022\005proto\"$\n\004User\022\n\n\002id\030\001 \001(\005\022" +
      "\020\n\010username\030\002 \001(\tB8\n\026com.limaopu.grpc.pr" +
      "otoB\tUserProtoP\001Z\021grpc-myboot/protob\006pro" +
      "to3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_proto_User_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_proto_User_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_User_descriptor,
        new java.lang.String[] { "Id", "Username", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
