<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service.proto

namespace Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>proto.RpcJsonRequest</code>
 */
class RpcJsonRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string route = 1;</code>
     */
    protected $route = '';
    /**
     * Generated from protobuf field <code>string data = 2;</code>
     */
    protected $data = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $route
     *     @type string $data
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Service::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string route = 1;</code>
     * @return string
     */
    public function getRoute()
    {
        return $this->route;
    }

    /**
     * Generated from protobuf field <code>string route = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setRoute($var)
    {
        GPBUtil::checkString($var, True);
        $this->route = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string data = 2;</code>
     * @return string
     */
    public function getData()
    {
        return $this->data;
    }

    /**
     * Generated from protobuf field <code>string data = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setData($var)
    {
        GPBUtil::checkString($var, True);
        $this->data = $var;

        return $this;
    }

}

