<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: user.proto

namespace GPBMetadata;

class User
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
{

user.protoproto"$
User

id (
username (	B8
com.limaopu.grpc.protoB	UserProtoPZgrpc-myboot/protobproto3'
        , true);

        static::$is_initialized = true;
    }
}

